export const ANATOMY = {
  TORSO: 90,
  TORSO_WIDTH: 37.5,
  PELVIS: 45,
  SHOULDER_WIDTH: 75,
  HIP_WIDTH: 60,
  NECK: 15,
  NECK_BASE: 15,
  HEAD: 45,
  HEAD_WIDTH: 18,
  UPPER_ARM: 60,
  LOWER_ARM: 60,
  HAND: 22.5,
  LEG_UPPER: 75,
  LEG_LOWER: 75,
  FOOT: 30,
  LIMB_WIDTH_ARM: 22.5,
  LIMB_WIDTH_FOREARM: 18,
  LIMB_WIDTH_THIGH: 30,
  LIMB_WIDTH_CALF: 22.5,
  EFFECTOR_WIDTH: 15,
};

export const HEAD_UNIT = ANATOMY.HEAD;

export const RIGGING = {
  SHOULDER_INSET: 7.5,
  SHOULDER_LIFT: 0,
  CLAVICLE_EXTENSION: 0,
  NECK_SINK: -7.5,
};
