export const ANATOMY = {
  ROOT_SIZE: 15,
  WAIST: 30, WAIST_WIDTH: 45,
  TORSO: 60, TORSO_WIDTH: 37.5,
  COLLAR: 15, COLLAR_WIDTH: 75,
  HEAD: 45, HEAD_WIDTH: 14,
  HEAD_BASE_WIDTH: 14, HEAD_TOP_WIDTH: 14,
  UPPER_ARM: 60, LOWER_ARM: 60, HAND: 22.5, HAND_WIDTH: 15,
  LEG_UPPER: 75, LEG_LOWER: 75, FOOT: 30, FOOT_WIDTH: 15,
  LIMB_WIDTH_ARM: 22.5, LIMB_WIDTH_FOREARM: 18,
  LIMB_WIDTH_THIGH: 30, LIMB_WIDTH_CALF: 22.5,
  EFFECTOR_WIDTH: 15,
  HEAD_NECK_GAP_OFFSET: 0,
};

export const RIGGING = {
  R_SHOULDER_X_OFFSET_FROM_COLLAR_CENTER: 30,
  L_SHOULDER_X_OFFSET_FROM_COLLAR_CENTER: -30,
  SHOULDER_Y_OFFSET_FROM_COLLAR_END: 0,
};

export const BASE_ROTATIONS: Record<string, number> = {
  bodyRotation: 0,
  waist: 0,
  torso: 0,
  collar: 0,
  head: 0,
  rShoulder: 0,
  rForearm: 0,
  rWrist: 0,
  lShoulder: 0,
  lForearm: 0,
  lWrist: 0,
  rThigh: 0,
  rCalf: 0,
  rAnkle: 0,
  lThigh: 0,
  lCalf: 0,
  lAnkle: 0,
};

export const TIPTOE = {
  TENSION_THRESHOLD: 45,
  ARCH_SCALE_MAX: 0.5,
};

export const COLORS = {
  ANCHOR_RED: "#F87171",
  SELECTION: "#D1D5DB",
  RIDGE: "#333333",
  PIN_HIGHLIGHT: "#D1D5DB",
  GREEN_CURL: "#A3E635",
  PURPLE_STRETCH: "#8B7EC1",
  EXTREMITY_WHITE: "#FFFFFF",
  MEDIUM_GRAY_BICEP: "#888888",
  DARKER_GRAY_FOREARM: "#555555",
  OLIVE_COLLAR: "#4B5320",
  CORE_MEDIUM_GRAY_TORSO: "#666666",
  CORE_LIGHT_GRAY_WAIST: "#AAAAAA",
  DARK_GRAY_THIGH: "#444444",
  VERY_DARK_GRAY_SHIN: "#222222",
  DEFAULT_FILL: "#000000",
  BACKLIGHT_OPACITY: 0.25,
  SHADOW: "rgba(0,0,0,0.1)",
  TENSION_PINK: "#FF69B4",
};
